[package]
name = "objdiff"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/encounter/objdiff"
readme = "README.md"
description = """
A tool for decompilation projects.
"""

[dependencies]
egui = "0.19.0"
eframe = { version = "0.19.0", features = ["persistence"] } # , "wgpu"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.63"
thiserror = "1.0.33"
flagset = "0.4.3"
object = "0.29.0"
notify = "5.0.0"
cwdemangle = "0.1.1"
log = "0.4.17"
rfd = { version = "0.10.0" } # , default-features = false, features = ['xdg-portal']
egui_extras = "0.19.0"
ppc750cl = { git = "https://github.com/terorie/ppc750cl" }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
